plot1/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^ex1/$', views.ex1, name="ex1"),
    url(r'^ex2/$', views.ex2, name="ex2"),
    url(r'^ex3/$', views.ex3, name="ex3"),
    url(r'^ex4/$', views.ex4, name="ex4"),
    url(r'^ex5/$', views.ex5, name="ex5"),
]

site1/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="index.html")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^plot1/', include('plot1.urls', namespace='plot1')),
]

craigslist/models.py
from django.db import models
from django.contrib.auth.models import User

class cl_Site(models.Model):
    name = models.CharField(max_length=255)
    url = models.URLField()

    def __unicode__(self):
        return self.name

class cl_Site_subSite(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField()
    cl_Site = models.ForeignKey(cl_Site)

class cl_Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField()

    def __unicode__(self):
        return self.name

class cl_Category_subCat(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField()
    cl_Category = models.ForeignKey(cl_Category)

    def __unicode__(self):
        return self.name

class cl_GleanQuery(models.Model):
    user = models.ManyToManyField(User)
    cl_Categories = models.ManyToManyField(cl_Category, blank=True)
    cl_Categories_subCat = models.ManyToManyField(cl_Category_subCat, blank=True)
    expiration_date = models.DateTimeField()
    creation_date = models.DateTimeField(auto_now=True)
    search_term = models.CharField(max_length=255)
    cl_Sites = models.ManyToManyField(cl_Site)
    cl_Sites_subSites = models.ManyToManyField(cl_Site_subSite, blank=True)
    notification_frequency = models.IntegerField()
    execution_frequency = models.IntegerField()
    last_execution = models.DateTimeField(null=True, blank=True)
    min_price = models.IntegerField(blank=True, null=True)
    max_price = models.IntegerField(blank=True, null=True)
    has_image = models.BooleanField()
    only_search_titles = models.BooleanField()
    active = models.BooleanField()

    def __unicode__(self):
        return self.search_term
    def number_Of_Results(self):
        return cl_GleanResult.objects.filter(cl_GleanQuery=self).count()
class cl_GleanResult(models.Model):
    title = models.CharField(max_length=255)
    posted = models.DateTimeField(blank=True, null=True)
    url = models.URLField(unique=True)
    image_url = models.URLField()
    location = models.CharField(max_length=255)
    gleaned_time = models.DateTimeField()
    telephone_number = models.CharField(max_length=25)
    reply_to_address = models.EmailField()
    cl_GleanQuery = models.ForeignKey(cl_GleanQuery)
    description = models.TextField()

    def __unicode__(self):
        return self.title

plot1/models.py
from django.db import models

# Create your models here.

craigslist/views.py
# Create your views here.

plot1/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.shortcuts import render
from . import views_util

# Bokeh
from bokeh.plotting import figure
from bokeh.resources import CDN
from bokeh.embed import components

def ex1(request):
    x = [1, 2, 3, 4, 5]
    y = [6, 7, 2, 4, 5]
    p = figure(title="simple line example", x_axis_label='x', y_axis_label='y')
    p.line(x, y, legend="Temp.", line_width=2)

    script, div = components(p, CDN)
    return render(request, "plot1/ex1.html", {"bokeh_script":script, "bokeh_div":div})

def ex2(request):
    x = [0.1, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0]
    y0 = [i**2 for i in x]
    y1 = [10**i for i in x]
    y2 = [10**(i**2) for i in x]

    # create a new plot
    p = figure(
       tools="pan,box_zoom,reset,save",
       y_axis_type="log", y_range=[0.001, 10**11], title="log axis example",
       x_axis_label='sections', y_axis_label='particles'
    )

    # add some renderers
    p.line(x, x, legend="y=x")
    p.circle(x, x, legend="y=x", fill_color="white", size=8)
    p.line(x, y0, legend="y=x^2", line_width=3)
    p.line(x, y1, legend="y=10^x", line_color="red")
    p.circle(x, y1, legend="y=10^x", fill_color="red", line_color="red", size=6)
    p.line(x, y2, legend="y=10^x^2", line_color="orange", line_dash="4 4")

    script, div = components(p, CDN)
    return render(request, "plot1/ex2.html", {"bokeh_script":script, "bokeh_div":div})

def ex3(request):
    p = views_util.plot3()

    script, div = components(p, CDN)
    return render(request, "plot1/ex3.html", {"bokeh_script":script, "bokeh_div":div})


def ex4(request):
    p = views_util.plot4()

    script, div = components(p, CDN)
    return render(request, "plot1/ex4.html", {"bokeh_script":script, "bokeh_div":div})

def ex5(request):
    p = views_util.plot5()

    script, div = components(p, CDN)
    return render(request, "plot1/ex5.html", {"bokeh_script":script, "bokeh_div":div})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Experiments with Postgres and Hstore</title>
    <script src="http://cdn.pydata.org/bokeh/release/bokeh-0.9.3.min.js"></script>
    <link rel="stylesheet" href="http://cdn.pydata.org/bokeh/release/bokeh-0.9.3.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
</head>

    <body>
    <div class="container">
    {% block content %}{% endblock content %}
    </div>
    </body>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</html>

templates/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <h2>Applied Ideas Sandbox</h2>
    </div>

    <div class="row">
        <ul class="list-group">
          <li class="list-group-item"><a class="btn btn-info" href="{% url 'plot1:ex1' %} ">Plot 1 Ex. 1</a></li>
          <li class="list-group-item"><a class="btn btn-info" href="{% url 'plot1:ex2' %} ">Plot 1 Ex. 2</a></li>
          <li class="list-group-item"><a class="btn btn-info" href="{% url 'plot1:ex3' %} ">Plot 1 Ex. 3</a></li>
          <li class="list-group-item"><a class="btn btn-info" href="{% url 'plot1:ex4' %} ">Plot 1 Ex. 4 (2D image)</a></li>
          <li class="list-group-item"><a class="btn btn-info" href="{% url 'plot1:ex5' %} ">Plot 1 Ex. 5 (2D scatter with color map dropdown selection)</a></li>
        </ul>
    </div>
</div>
<div class="container-fluid">
  <img src="{% static "science.gif" %}" class="img-circle" alt="Bokeh" >
</div>
{% endblock content %}

templates/plot1/ex1.html
{% extends "base.html" %}

{% block content %}
    <h2>Example 1 with Bokeh</h2>

    {{bokeh_div|safe}}

    {{bokeh_script|safe}}

{% endblock content %}

templates/plot1/ex2.html
{% extends "base.html" %}

{% block content %}
    <h2>Example 2 with Bokeh</h2>

    {{bokeh_div|safe}}

    {{bokeh_script|safe}}

{% endblock content %}

templates/plot1/ex3.html
{% extends "base.html" %}

{% block content %}
    <h2>Example 3 with Bokeh</h2>

    <p>Visualize the evolution of the temperature anomaly monthly average over time with a timeseries chart</p>
    {{bokeh_div|safe}}

    {{bokeh_script|safe}}

{% endblock content %}

templates/plot1/ex4.html
{% extends "base.html" %}

{% block content %}
    <h2>Example 4 with Bokeh</h2>

    <p>2D regular plot (image)</p>
    {{bokeh_div|safe}}

    {{bokeh_script|safe}}

{% endblock content %}

templates/plot1/ex5.html
{% extends "base.html" %}

{% block content %}
    <h2>Example 4 with Bokeh</h2>

    <p>2D plot built from a scatter plot</p>
    {{bokeh_div|safe}}

    {{bokeh_script|safe}}

{% endblock content %}